module.exports=[71618,a=>{a.v({button:"Button-module__8RiFmG__button",fullWidth:"Button-module__8RiFmG__fullWidth",ghost:"Button-module__8RiFmG__ghost",lg:"Button-module__8RiFmG__lg",md:"Button-module__8RiFmG__md",outline:"Button-module__8RiFmG__outline",primary:"Button-module__8RiFmG__primary",secondary:"Button-module__8RiFmG__secondary",sm:"Button-module__8RiFmG__sm"})},96438,a=>{"use strict";var b=a.i(87924),c=a.i(72131),d=a.i(71618);let e=c.default.forwardRef(({className:a="",variant:c="primary",size:e="md",fullWidth:f=!1,children:g,...h},i)=>{let j=[d.default.button,d.default[c],d.default[e],f?d.default.fullWidth:"",a].filter(Boolean).join(" ");return(0,b.jsx)("button",{ref:i,className:j,...h,children:g})});e.displayName="Button",a.s(["Button",0,e])},63073,a=>{"use strict";var b=a.i(87924),c=a.i(72131),d=a.i(38246),e=a.i(50944),f=a.i(38393),g=a.i(96438);function h({children:a}){let h=(0,e.usePathname)(),i=(0,e.useRouter)(),{user:j,isLoading:k,logout:l}=(0,f.useAuth)(),[m,n]=(0,c.useState)(!1);if((0,c.useEffect)(()=>{},[h]),(0,c.useEffect)(()=>{},[h]),"/staff/login"===h)return(0,b.jsx)(b.Fragment,{children:a});if(k)return(0,b.jsx)("div",{style:{display:"flex",justifyContent:"center",alignItems:"center",minHeight:"100vh"},children:"Loading..."});if(!j||"admin"!==j.role&&"staff"!==j.role)return i.push("/staff/login"),null;let o=a=>({display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.75rem 1rem",borderRadius:"0.5rem",color:a?"#1d4ed8":"#374151",backgroundColor:a?"#dbeafe":"transparent",fontWeight:a?500:400,textDecoration:"none",whiteSpace:"nowrap"});return(0,b.jsxs)(b.Fragment,{children:[(0,b.jsx)("style",{dangerouslySetInnerHTML:{__html:`
                .staff-layout { display: flex; min-height: calc(100vh - 64px); align-items: flex-start; }
                .staff-sidebar { width: 240px; background-color: #f0f9ff; border-right: 1px solid #bfdbfe; display: flex; flex-direction: column; flex-shrink: 0; overflow-y: auto; position: sticky; top: 64px; height: calc(100vh - 64px); z-index: 40; margin-left: 0; transition: margin-left 0.3s; }
                .staff-sidebar:not(.open) { margin-left: -240px; }
                .staff-main-wrapper { flex: 1; display: flex; flex-direction: column; min-width: 0; width: 100%; }
                .staff-top-bar { display: flex; align-items: center; padding: 1rem 1.5rem; background-color: white; border-bottom: 1px solid #bfdbfe; position: sticky; top: 64px; z-index: 30; }
                .staff-main { padding: 1rem; flex: 1; background-color: white; }
                .staff-backdrop { display: none; }
                @media (max-width: 767px) {
                    .staff-layout { padding-bottom: 5rem; }
                    .staff-sidebar { position: fixed; top: 0; left: 0; bottom: 0; height: 100vh; padding: 1.5rem; z-index: 9999; margin-left: 0 !important; transform: translateX(-100%); transition: transform 0.3s; }
                    .staff-sidebar.open { transform: translateX(0); }
                    .staff-backdrop { display: block; position: fixed; top: 0; left: 0; right: 0; bottom: 0; background-color: rgba(0,0,0,0.5); z-index: 9998; opacity: 0; visibility: hidden; transition: opacity 0.3s, visibility 0.3s; }
                    .staff-backdrop.open { opacity: 1; visibility: visible; }
                    .staff-top-bar { position: relative; top: 0; }
                }
                @media (min-width: 768px) { .staff-main { padding: 2rem; } }
            `}}),(0,b.jsxs)("div",{className:"staff-layout",children:[(0,b.jsx)("div",{className:`staff-backdrop ${m?"open":""}`,onClick:()=>n(!1)}),(0,b.jsx)("aside",{className:`staff-sidebar ${m?"open":""}`,children:(0,b.jsxs)("div",{style:{display:"flex",flexDirection:"column",height:"100%",padding:"1.5rem 1rem"},children:[(0,b.jsxs)("div",{style:{marginBottom:"1.5rem"},children:[(0,b.jsx)("h2",{style:{fontSize:"1.25rem",fontWeight:"bold",color:"#1d4ed8",margin:0},children:"🧑‍💼 Staff Panel"}),j&&(0,b.jsxs)("p",{style:{fontSize:"0.75rem",color:"#6b7280",marginTop:"0.25rem"},children:[j.firstName," ",j.lastName]})]}),(0,b.jsxs)("nav",{style:{display:"flex",flexDirection:"column",gap:"0.5rem",flex:1},children:[(0,b.jsx)("div",{style:{fontSize:"0.7rem",fontWeight:"bold",color:"#9ca3af",textTransform:"uppercase",paddingLeft:"0.5rem",marginBottom:"0.25rem"},children:"จัดการออเดอร์"}),(0,b.jsxs)(d.default,{href:"/staff/orders",style:o("/staff/orders"===h),children:[(0,b.jsx)("span",{style:{fontSize:"1.1rem"},children:"🛒"})," ออเดอร์ทั้งหมด"]}),(0,b.jsxs)(d.default,{href:"/staff/reviews",style:o("/staff/reviews"===h),children:[(0,b.jsx)("span",{style:{fontSize:"1.1rem"},children:"⭐"})," จัดการรีวิว"]})]}),(0,b.jsx)("div",{style:{marginTop:"auto",paddingTop:"1rem",borderTop:"1px solid #bfdbfe"},children:(0,b.jsx)(g.Button,{variant:"outline",fullWidth:!0,onClick:l,style:{borderColor:"#1d4ed8",color:"#1d4ed8"},children:"ออกจากระบบ"})})]})}),(0,b.jsxs)("div",{className:"staff-main-wrapper",children:[(0,b.jsxs)("div",{className:"staff-top-bar",children:[(0,b.jsx)("button",{onClick:()=>n(!m),style:{padding:"0.5rem",marginRight:"1rem",backgroundColor:"white",border:"1px solid #bfdbfe",borderRadius:"0.375rem",display:"flex",alignItems:"center",cursor:"pointer"},children:(0,b.jsx)("svg",{width:"20",height:"20",fill:"none",stroke:"#1d4ed8",viewBox:"0 0 24 24",children:(0,b.jsx)("path",{strokeLinecap:"round",strokeLinejoin:"round",strokeWidth:"2",d:"M4 6h16M4 12h16M4 18h16"})})}),(0,b.jsx)("h1",{style:{fontSize:"1.25rem",fontWeight:600,color:"#1d4ed8",margin:0},children:"พนักงาน (Staff)"})]}),(0,b.jsx)("main",{className:"staff-main",children:a})]})]})]})}a.s(["default",()=>h])}];

//# sourceMappingURL=src_65d02ade._.js.map