export const MOCK_TREES = [
  {
    id: '86689128-236e-41d7-9b28-ac157ed62766',
    name: 'กวักพระพรหม',
    sku: 'B005',
    price: 350,
    originalPrice: null,
    description: 'ไม้มงคลหายาก เสริมสิริมงคล',
    images: JSON.stringify(['/images/products/system_plants/kwak_phra_phrom/kwak_phra_phrom_1.jpg']),
    category: 'ไม้มงคล',
    status: 'AVAILABLE',
    stock: 19,
    reserved: 1,
    sold: 1,
    rating: 4,
    reviewCount: 1,
    isPromotion: false,
    promotionName: null,
    promotionEndDate: null,
    tags: 'ไม้มงคล,หายาก',
    growthTime: '1–2 อาทิตย์',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '69abe344-321c-46c9-ab9d-918f44edd251',
    name: 'คุ้มภัย',
    sku: 'A005',
    price: 50,
    originalPrice: null,
    description: 'ต้นไม้ขนาดเล็ก เหมาะสำหรับตกแต่งในออฟฟิศ',
    images: JSON.stringify(['/images/products/system_plants/khum_phai/khum_phai_1.jpg']),
    category: 'ไม้มงคล',
    status: 'AVAILABLE',
    stock: 15,
    reserved: 0,
    sold: 0,
    rating: 0,
    reviewCount: 0,
    isPromotion: false,
    promotionName: null,
    promotionEndDate: null,
    tags: 'ไม้มงคล,ขนาดเล็ก',
    growthTime: '1–2 อาทิตย์',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'dcaff166-0e1c-4296-a9b8-ef785f01ce13',
    name: 'มรดกโลก',
    sku: 'B007',
    price: 1500,
    originalPrice: null,
    description: 'ไม้ประดับใบสวย ทรงพุ่มสง่า เหมาะสำหรับตกแต่งห้องนั่งเล่นหรือมุมทำงาน',
    images: JSON.stringify(['/images/products/system_plants/moradok_lok/moradok_lok_1.jpg']),
    category: 'ไม้ประดับ',
    status: 'AVAILABLE',
    stock: 8,
    reserved: 0,
    sold: 15,
    rating: 4.9,
    reviewCount: 20,
    isPromotion: true,
    promotionName: 'Flash Sale',
    promotionEndDate: null,
    tags: 'ไม้ดอก,ฮิต',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-4',
    name: 'กวักพระพรหม',
    sku: 'B006',
    price: 150,
    originalPrice: null,
    description: 'ไม้มงคลเชื่อว่าเรียกทรัพย์ เลี้ยงง่ายมาก ไม่ต้องรดน้ำบ่อย',
    images: JSON.stringify(['/images/products/กวักพระพรหม/กวักพระพรหม.jpg']),
    category: 'ไม้มงคล',
    status: 'AVAILABLE',
    stock: 20,
    reserved: 0,
    sold: 8,
    rating: 4.2,
    reviewCount: 3,
    isPromotion: false,
    promotionName: null,
    promotionEndDate: null,
    tags: 'มงคล,ทนทาน',
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export const MOCK_REVIEWS = [
  {
    id: 'mock-rev-1',
    rating: 5,
    comment: 'ต้นไม้สวยมากครับ แพ็คมาดีไม่มีช้ำเลย (Mock Review)',
    userId: 'mock-user-1',
    treeId: 'mock-1',
    createdAt: new Date(),
    isFeatured: true,
    hidden: false,
    user: {
      firstName: 'สมชาย',
      lastName: 'รักต้นไม้'
    }
  },
  {
    id: 'mock-rev-2',
    rating: 4,
    comment: 'ส่งไวมากครับ แอดมินตอบคำถามดี (Mock Review)',
    userId: 'mock-user-2',
    treeId: 'mock-2',
    createdAt: new Date(),
    isFeatured: true,
    hidden: false,
    user: {
      firstName: 'วิภา',
      lastName: 'ใจดี'
    }
  }
];

export const MOCK_SITE_SETTINGS = {
  hero_title: 'สวนสวยเริ่มต้นที่ สวนคุณแดง (Demo Mode)',
  hero_subtitle: 'ขณะนี้เว็บไซต์กำลังแสดงผลในโหมดตัวอย่าง (Demo) เนื่องจากไม่สามารถเชื่อมต่อฐานข้อมูลได้',
  hero_tag: '#MockDataMode',
  top_bar_text: 'ระบบกำลังทำงานในโหมด Demo'
};
