var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/activities/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e25571b4._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_a28ffcb4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__28878103._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f68cf2f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8d2ca5d5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_admin_layout_tsx_07d69fb5._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_activities_page_actions_cacf1172.js")
R.m(22887)
module.exports=R.m(22887).exports
