// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/activities" | "/admin/dashboard" | "/admin/inventory" | "/admin/login" | "/admin/orders" | "/admin/orders/[status]" | "/admin/promotions" | "/admin/reports" | "/admin/reports/best-sellers" | "/admin/reports/orders" | "/admin/reports/sales" | "/admin/reports/status-breakdown" | "/admin/reports/trees-sold" | "/admin/reviews" | "/admin/settings" | "/admin/trees" | "/admin/users" | "/admin/verify" | "/articles" | "/best-sellers" | "/booking-success" | "/cart" | "/consultation" | "/contact" | "/customer-service" | "/faq" | "/favorites" | "/forgot-password" | "/how-to-order" | "/login" | "/logout" | "/notifications" | "/orders" | "/profile" | "/profile/bookings" | "/promotion" | "/register" | "/reset-password" | "/services" | "/shop" | "/shop/[id]" | "/staff/login" | "/staff/orders" | "/staff/reviews" | "/tech-stack" | "/trees/[id]" | "/verify-email" | "/weekly-best-sellers"
type AppRouteHandlerRoutes = "/api/admin/bookings/[id]/action" | "/api/admin/bookings/[id]/approve" | "/api/admin/categories" | "/api/admin/notifications" | "/api/admin/reviews" | "/api/admin/reviews/[id]" | "/api/admin/trees/[id]/stock" | "/api/auth/admin-magic-link" | "/api/auth/admin-verify" | "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/me" | "/api/auth/register" | "/api/auth/reset-password" | "/api/auth/verify" | "/api/auth/verify-reset-code" | "/api/auth/verify-reset-token" | "/api/bookings" | "/api/bookings/[id]" | "/api/bookings/[id]/cancel" | "/api/contact" | "/api/favorites" | "/api/logout" | "/api/notifications" | "/api/notifications/email" | "/api/reviews" | "/api/reviews/[id]" | "/api/reviews/[id]/helpful" | "/api/run-category-update" | "/api/settings" | "/api/trees" | "/api/trees/[id]" | "/api/trees/best-sellers" | "/api/trees/weekly-best-sellers" | "/api/upload" | "/api/upload/images" | "/api/uploads/[filename]" | "/api/users" | "/api/users/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/staff"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/activities": {}
  "/admin/dashboard": {}
  "/admin/inventory": {}
  "/admin/login": {}
  "/admin/orders": {}
  "/admin/orders/[status]": { "status": string; }
  "/admin/promotions": {}
  "/admin/reports": {}
  "/admin/reports/best-sellers": {}
  "/admin/reports/orders": {}
  "/admin/reports/sales": {}
  "/admin/reports/status-breakdown": {}
  "/admin/reports/trees-sold": {}
  "/admin/reviews": {}
  "/admin/settings": {}
  "/admin/trees": {}
  "/admin/users": {}
  "/admin/verify": {}
  "/api/admin/bookings/[id]/action": { "id": string; }
  "/api/admin/bookings/[id]/approve": { "id": string; }
  "/api/admin/categories": {}
  "/api/admin/notifications": {}
  "/api/admin/reviews": {}
  "/api/admin/reviews/[id]": { "id": string; }
  "/api/admin/trees/[id]/stock": { "id": string; }
  "/api/auth/admin-magic-link": {}
  "/api/auth/admin-verify": {}
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/auth/verify": {}
  "/api/auth/verify-reset-code": {}
  "/api/auth/verify-reset-token": {}
  "/api/bookings": {}
  "/api/bookings/[id]": { "id": string; }
  "/api/bookings/[id]/cancel": { "id": string; }
  "/api/contact": {}
  "/api/favorites": {}
  "/api/logout": {}
  "/api/notifications": {}
  "/api/notifications/email": {}
  "/api/reviews": {}
  "/api/reviews/[id]": { "id": string; }
  "/api/reviews/[id]/helpful": { "id": string; }
  "/api/run-category-update": {}
  "/api/settings": {}
  "/api/trees": {}
  "/api/trees/[id]": { "id": string; }
  "/api/trees/best-sellers": {}
  "/api/trees/weekly-best-sellers": {}
  "/api/upload": {}
  "/api/upload/images": {}
  "/api/uploads/[filename]": { "filename": string; }
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/articles": {}
  "/best-sellers": {}
  "/booking-success": {}
  "/cart": {}
  "/consultation": {}
  "/contact": {}
  "/customer-service": {}
  "/faq": {}
  "/favorites": {}
  "/forgot-password": {}
  "/how-to-order": {}
  "/login": {}
  "/logout": {}
  "/notifications": {}
  "/orders": {}
  "/profile": {}
  "/profile/bookings": {}
  "/promotion": {}
  "/register": {}
  "/reset-password": {}
  "/services": {}
  "/shop": {}
  "/shop/[id]": { "id": string; }
  "/staff": {}
  "/staff/login": {}
  "/staff/orders": {}
  "/staff/reviews": {}
  "/tech-stack": {}
  "/trees/[id]": { "id": string; }
  "/verify-email": {}
  "/weekly-best-sellers": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/staff": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
