var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/trees/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__7111dc5e._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_7079b7f9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__28878103._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f68cf2f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8d2ca5d5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_admin_layout_tsx_07d69fb5._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_trees_page_actions_9ac1b1ee.js")
R.m(53957)
module.exports=R.m(53957).exports
