var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/admin-magic-link/route.js")
R.c("server/chunks/[root-of-the-server]__532559b3._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_accb2806._.js")
R.c("server/chunks/[root-of-the-server]__24f8fcd9._.js")
R.c("server/chunks/[root-of-the-server]__09f97b47._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/_next-internal_server_app_api_auth_admin-magic-link_route_actions_8ec49cde.js")
R.m(74641)
module.exports=R.m(74641).exports
